<div ng-controller="ActivityCtrl as hctrl">
	<div class="info" ng-show="showForm">
			<p><input name="fName" type="text" ng-model="form.firstName" placeholder="First Name" /></p>
			<p><input name="lName" type="text" ng-model="form.lastName" placeholder="Last Name" /></p>
			<p><input name="eMail" type="text" ng-model="form.email" placeholder="Email" /></p>
			<p><input name="password" type="text" ng-model="form.password" placeholder="Password" /></p>

			<p style="margin-left: 40%;"> Status:
				<select id="comboBox" class="combobox" ng-model="form.selectStatus">
					<option value="" style="display:none;"></option>
					<option value="Admin" ng-selected="true">Admin</option>
					<option value="Guest">Guest</option>
				</select>
			</p>

			<button ng-click="setData()">Save</button>
			<button ng-click="closeForm()">Close</button>
		</p>
	</div>

	<div class="details">
		<div class="tableTop">
			<div class="crudButtons">
				<p style="float: left;">
					<button ng-click="showForm = true;">Add</button>
					<button ng-click="getInfo()">Edit</button>
					<button ng-click="deleteData()">Delete</button>
				</p>
			</div>

			<div class="searchPart">
				<p style="float: right;">
					<input type="text" placeholder="Search Last Name" ng-model="search" ng-change="filterData(search)" />
					<select id="filterbyStatus" ng-model="form.filterStatus" ng-change="filterStatus(form.filterStatus)">
						<option value="" style="display:none;"></option>
						<option value="All" ng-selected="true">All</option>
						<option value="Admin">Admin</option>
						<option value="Guest">Guest</option>
					</select>
					<!-- <button ng-click="searchData(search)">Search</button> -->
					<!-- <button ng-click="getData()">Cancel</button> -->
				</p>
			</div>
		</div>

		<div class="records">
			<table>
				<thead>
					<tr>
						<th style="width: 2%; text-align: center">
							<input type="checkbox" class="all-checkbox" ng-click="selectAll($event);">
						</th>
						<th style="width: 20%; text-align: center;">Last Name</th>
						<th style="width: 20%; text-align: center;">First Name</th>
						<th style="width: 20%; text-align: center;">Email</th>
						<th style="width: 20%; text-align: center;">Password</th>
						<th style="width: 20%; text-align: center;">Status</th>
					</tr>
				</thead>

				<tbody ng-repeat="user in users">
					<td style="text-align: center"><input type="checkbox" class="checkbox" value="{{ user.id }}"></td>
					<td style="text-align: center"> {{ user.lastName }} </td>
					<td style="text-align: center"> {{ user.firstName }} </td>
					<td style="text-align: center"> {{ user.email }} </td>
					<td style="text-align: center"> {{ user.password }} </td>
					<td style="text-align: center"> {{ user.status }} </td>
				</tbody>
			</table>
		</div>
	</div>
</div>
