<div ng-controller="LoginCtrl as lctrl" class="container">

	<button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-green w3-large">Login</button>

	<div id="id01" class="w3-modal">
	    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">

		    <div class="w3-center"><br>
		        <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
		        <img src="http://www.newdesignfile.com/postpic/2014/06/avatar-icon_249320.png" alt="Avatar" style="width:30%" class="w3-circle w3-margin-top">
		    </div>

		      <form class="w3-container">
		        <div class="w3-section">
		          <label><b>Email</b></label><input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter Email" required ng-model="form.email">
		          <label><b>Password</b></label><input class="w3-input w3-border" type="password" placeholder="Enter Password" required ng-model="form.password">
		          <button class="w3-button w3-block w3-green w3-section w3-padding" type="button" ng-click="loginData()">Login</button>
		        </div>
		      </form>
		</div>
	</div>

	<!-- <div id="body" class="body">
		<p><input class="log" type="text" ng-model="form.email" placeholder="Email" /></p>
		<p><input class="log" type="password" ng-model="form.password" placeholder="Password" /></p>

		<p>
			<button type="button" class="btn" ng-click="loginData()">Submit</button>
		</p>
	</div> -->
	<!-- <span><?php //echo $this->session->get("username"); ?></span> -->
</div>
